### ISSUE TITLE
Interface Confusing

### ISSUE THREAD

**Issue by hightechhostel** [BadPirate/pgewall#1]
Thanks for making this simulator.  I would very much like to use it but I'm confused.  

1.  My CSV from PG&E is not parsing correctly.  Please provide the format you would like to see the CSV in. 
2.  It seems the simulator will only accept solar production or battery storage but not both at the same time.  You only see battery storage options of you disable the solar calculator.  

We are considering a small amount of solar and a lot of battery storage because we want to do energy arbitrage.  Thanks for your help.

**Comment by BadPirate** [comment]
> Thanks for making this simulator. I would very much like to use it but I'm confused.
> 
> 1. My CSV from PG&E is not parsing correctly.  Please provide the format you would like to see the CSV in.

Make sure to choose "Energy Details" on export, it's the one that has hourly usage:

Choosing "Energy Details" button
Clicking the "Green Button" to Download my data
Choosing "Export Usage for a Range"
Setting range (A full year is needed for ROI prediction, but less will still provide data)
Clicking Export

> 2. It seems the simulator will only accept solar production or battery storage but not both at the same time.  You only see battery storage options of you disable the solar calculator.

If you don't have solar data it won't show battery storage options.

> 
> We are considering a small amount of solar and a lot of battery storage because we want to do energy arbitrage. Thanks for your help.

Readme and the associated medium article might help you understand the broader implications. https://github.com/BadPirate/pgewall

Finally, the source is available, right now I made the tool mostly to explore my specific scenario (PGE & Enphase Enlighten for solar), but the code (ugly as it is) is open.

**Comment by hightechhostel** [comment]
Thanks for this information.  It seems like something has broken on this app or I just am being an idiot and I'm unable to figure it out.  Here's a video showing my problem:   https://youtu.be/WL-qRgsCeSY

As I say at the beginning of the video, I will understand if you don't have time to answer these questions.  If this is the case, just let me know.

**Comment by BadPirate** [comment]
Thanks for the video.

If you feel comfortable send me the CSV you got from PGE, feel free to trim
the top rows (that have your personal info on it) and I can see if there
was some kind of a format change.  If your data is right then it will
populate all those other fields (and show more than "0 rows").

You can see more details by turning on the "Console" in your browser ("View
-> Developer -> Javascript Console" in chrome) as well.

badpirate@gmail.com

**Comment by BadPirate** [comment]
A few issues discovered here thanks to @hightechhostel 

UI / Interface lacks useful feedback when CSV fails to parse / invalid format (This ticket)

PG&E changed CSV format from 7 -> 8 column, this needs to work gracefully #2 (Root Cause)

Solar Simulator no longer working #3 (Discovered during troubleshooting)

**Comment by hightechhostel** [comment]
Thanks, @BadPirate!  Things look much better with the valid CSV.  

https://www.loom.com/share/4e6848f3603846edb7de97b8f29bf349

**Comment by BadPirate** [comment]
Responding to your video:

1. Glad you were able to get it working for you!
2. Very much recommend using a whole year of CSV data when trying to do 10
year estimates, as seasonality is a huge factor in electric usage
3. "Split day" does work (pretty sure) but if not feel free to file an issue
4. Tooltips would be a good idea, specifically:
  - 10 Year capacity: is because batteries "Decay" over time, Tesla has
said that powerwall is Guaranteed to be at least 70% as effective after 10
years of use.  (.7). I left this variable in case you wanted to be less
conservative in cost estimations.
  - Round Trip Efficiency:  Batteries don't return 100% of the power pulled
from grid, there are losses.  Tesla estimates their inverter loss at 10%
(.9 efficiency), again left variable so that you could be more or less
conservative

Regarding 10 year returns, one factor I forgot to include is that PG&E has
averaged 6% increase in the overall cost for electric every year for the
last decade + -- So likely net savings will be higher, and there is
currently no way to include this factor I believe.

Feel free to make a YouTube howto, I think I did one at some point, but
better to have something described from a "novice" standpoint -- Let me
know and I'll link it from the README

**Comment by BadPirate** [comment]
Interface improved.
